/* Country list extracted verbatim from the Zoho export (Address_Country select).
 * Regenerate from index.zoho-export.html if Zoho's list changes.
 *
 * `name` is what the customer sees; `code` (ISO 3166-1 alpha-3) is what gets
 * submitted — the ERP matches countries by code, not by name.
 *
 * Zoho's list is the CIA World Factbook roster, which contains territories ISO
 * never assigned a code to. Those resolve as follows:
 *   - Included in a parent per ISO's own inclusion notes: Ashmore and Cartier /
 *     Coral Sea -> AUS, Clipperton -> FRA, Jan Mayen / Svalbard -> SJM,
 *     Navassa / Wake -> UMI, the Scattered Islands (Bassas da India, Europa,
 *     Glorioso, Juan de Nova, Tromelin) -> ATF, Gaza Strip / West Bank -> PSE.
 *   - Kosovo -> XKX (user-assigned; the EU/World Bank convention — no official
 *     ISO code exists).
 *   - Netherlands Antilles -> ANT (withdrawn from ISO in 2010 but still the
 *     only code that ever meant this entry).
 *   - No code exists at all (disputed / UK base areas): Akrotiri, Dhekelia,
 *     Paracel Islands, Spratly Islands — these submit their name unchanged,
 *     flagged with noIso below.
 */
var SW_COUNTRIES = [
  { name: "Afghanistan", code: "AFG" },
  { name: "Akrotiri", code: "Akrotiri", noIso: true },
  { name: "Albania", code: "ALB" },
  { name: "Algeria", code: "DZA" },
  { name: "American Samoa", code: "ASM" },
  { name: "Andorra", code: "AND" },
  { name: "Angola", code: "AGO" },
  { name: "Anguilla", code: "AIA" },
  { name: "Antarctica", code: "ATA" },
  { name: "Antigua and Barbuda", code: "ATG" },
  { name: "Argentina", code: "ARG" },
  { name: "Armenia", code: "ARM" },
  { name: "Aruba", code: "ABW" },
  { name: "Ashmore and Cartier Islands", code: "AUS" },
  { name: "Australia", code: "AUS" },
  { name: "Austria", code: "AUT" },
  { name: "Azerbaijan", code: "AZE" },
  { name: "Bahrain", code: "BHR" },
  { name: "Bangladesh", code: "BGD" },
  { name: "Barbados", code: "BRB" },
  { name: "Bassas Da India", code: "ATF" },
  { name: "Belarus", code: "BLR" },
  { name: "Belgium", code: "BEL" },
  { name: "Belize", code: "BLZ" },
  { name: "Benin", code: "BEN" },
  { name: "Bermuda", code: "BMU" },
  { name: "Bhutan", code: "BTN" },
  { name: "Bolivia", code: "BOL" },
  { name: "Bosnia and Herzegovina", code: "BIH" },
  { name: "Botswana", code: "BWA" },
  { name: "Bouvet Island", code: "BVT" },
  { name: "Brazil", code: "BRA" },
  { name: "British Indian Ocean Territory", code: "IOT" },
  { name: "British Virgin Islands", code: "VGB" },
  { name: "Brunei", code: "BRN" },
  { name: "Bulgaria", code: "BGR" },
  { name: "Burkina Faso", code: "BFA" },
  { name: "Burma", code: "MMR" },
  { name: "Burundi", code: "BDI" },
  { name: "Cambodia", code: "KHM" },
  { name: "Cameroon", code: "CMR" },
  { name: "Canada", code: "CAN" },
  { name: "Cape Verde", code: "CPV" },
  { name: "Caribbean Netherlands", code: "BES" },
  { name: "Cayman Islands", code: "CYM" },
  { name: "Central African Republic", code: "CAF" },
  { name: "Chad", code: "TCD" },
  { name: "Chile", code: "CHL" },
  { name: "China", code: "CHN" },
  { name: "Christmas Island", code: "CXR" },
  { name: "Clipperton Island", code: "FRA" },
  { name: "Cocos (Keeling) Islands", code: "CCK" },
  { name: "Colombia", code: "COL" },
  { name: "Comoros", code: "COM" },
  { name: "Cook Islands", code: "COK" },
  { name: "Coral Sea Islands", code: "AUS" },
  { name: "Costa Rica", code: "CRI" },
  { name: "Cote D'Ivoire", code: "CIV" },
  { name: "Croatia", code: "HRV" },
  { name: "Cuba", code: "CUB" },
  { name: "Curaçao", code: "CUW" },
  { name: "Cyprus", code: "CYP" },
  { name: "Czech Republic", code: "CZE" },
  { name: "Democratic Republic of the Congo", code: "COD" },
  { name: "Denmark", code: "DNK" },
  { name: "Dhekelia", code: "Dhekelia", noIso: true },
  { name: "Djibouti", code: "DJI" },
  { name: "Dominica", code: "DMA" },
  { name: "Dominican Republic", code: "DOM" },
  { name: "Ecuador", code: "ECU" },
  { name: "Egypt", code: "EGY" },
  { name: "El Salvador", code: "SLV" },
  { name: "Equatorial Guinea", code: "GNQ" },
  { name: "Eritrea", code: "ERI" },
  { name: "Estonia", code: "EST" },
  { name: "Ethiopia", code: "ETH" },
  { name: "Europa Island", code: "ATF" },
  { name: "Falkland Islands (Islas Malvinas)", code: "FLK" },
  { name: "Faroe Islands", code: "FRO" },
  { name: "Federated States of Micronesia", code: "FSM" },
  { name: "Fiji", code: "FJI" },
  { name: "Finland", code: "FIN" },
  { name: "France", code: "FRA" },
  { name: "French Guiana", code: "GUF" },
  { name: "French Polynesia", code: "PYF" },
  { name: "French Southern and Antarctic Lands", code: "ATF" },
  { name: "Gabon", code: "GAB" },
  { name: "Gaza Strip", code: "PSE" },
  { name: "Georgia", code: "GEO" },
  { name: "Germany", code: "DEU" },
  { name: "Ghana", code: "GHA" },
  { name: "Gibraltar", code: "GIB" },
  { name: "Glorioso Islands", code: "ATF" },
  { name: "Greece", code: "GRC" },
  { name: "Greenland", code: "GRL" },
  { name: "Grenada", code: "GRD" },
  { name: "Guadeloupe", code: "GLP" },
  { name: "Guam", code: "GUM" },
  { name: "Guatemala", code: "GTM" },
  { name: "Guernsey", code: "GGY" },
  { name: "Guinea", code: "GIN" },
  { name: "Guinea-bissau", code: "GNB" },
  { name: "Guyana", code: "GUY" },
  { name: "Haiti", code: "HTI" },
  { name: "Heard Island and Mcdonald Islands", code: "HMD" },
  { name: "Holy See (Vatican City)", code: "VAT" },
  { name: "Honduras", code: "HND" },
  { name: "Hong Kong", code: "HKG" },
  { name: "Hungary", code: "HUN" },
  { name: "Iceland", code: "ISL" },
  { name: "India", code: "IND" },
  { name: "Indonesia", code: "IDN" },
  { name: "Iran", code: "IRN" },
  { name: "Iraq", code: "IRQ" },
  { name: "Ireland", code: "IRL" },
  { name: "Isle of Man", code: "IMN" },
  { name: "Israel", code: "ISR" },
  { name: "Italy", code: "ITA" },
  { name: "Jamaica", code: "JAM" },
  { name: "Jan Mayen", code: "SJM" },
  { name: "Japan", code: "JPN" },
  { name: "Jersey", code: "JEY" },
  { name: "Jordan", code: "JOR" },
  { name: "Juan De Nova Island", code: "ATF" },
  { name: "Kazakhstan", code: "KAZ" },
  { name: "Kenya", code: "KEN" },
  { name: "Kiribati", code: "KIR" },
  { name: "Kosovo", code: "XKX" },
  { name: "Kuwait", code: "KWT" },
  { name: "Kyrgyzstan", code: "KGZ" },
  { name: "Laos", code: "LAO" },
  { name: "Latvia", code: "LVA" },
  { name: "Lebanon", code: "LBN" },
  { name: "Lesotho", code: "LSO" },
  { name: "Liberia", code: "LBR" },
  { name: "Libya", code: "LBY" },
  { name: "Liechtenstein", code: "LIE" },
  { name: "Lithuania", code: "LTU" },
  { name: "Luxembourg", code: "LUX" },
  { name: "Macau", code: "MAC" },
  { name: "Macedonia", code: "MKD" },
  { name: "Madagascar", code: "MDG" },
  { name: "Malawi", code: "MWI" },
  { name: "Malaysia", code: "MYS" },
  { name: "Maldives", code: "MDV" },
  { name: "Mali", code: "MLI" },
  { name: "Malta", code: "MLT" },
  { name: "Marshall Islands", code: "MHL" },
  { name: "Martinique", code: "MTQ" },
  { name: "Mauritania", code: "MRT" },
  { name: "Mauritius", code: "MUS" },
  { name: "Mayotte", code: "MYT" },
  { name: "Mexico", code: "MEX" },
  { name: "Moldova", code: "MDA" },
  { name: "Monaco", code: "MCO" },
  { name: "Mongolia", code: "MNG" },
  { name: "Montenegro", code: "MNE" },
  { name: "Montserrat", code: "MSR" },
  { name: "Morocco", code: "MAR" },
  { name: "Mozambique", code: "MOZ" },
  { name: "Myanmar", code: "MMR" },
  { name: "Namibia", code: "NAM" },
  { name: "Nauru", code: "NRU" },
  { name: "Navassa Island", code: "UMI" },
  { name: "Nepal", code: "NPL" },
  { name: "Netherlands Antilles", code: "ANT" },
  { name: "Netherlands", code: "NLD" },
  { name: "New Caledonia", code: "NCL" },
  { name: "New Zealand", code: "NZL" },
  { name: "Nicaragua", code: "NIC" },
  { name: "Niger", code: "NER" },
  { name: "Nigeria", code: "NGA" },
  { name: "Niue", code: "NIU" },
  { name: "Norfolk Island", code: "NFK" },
  { name: "North Korea", code: "PRK" },
  { name: "Northern Mariana Islands", code: "MNP" },
  { name: "Norway", code: "NOR" },
  { name: "Oman", code: "OMN" },
  { name: "Pakistan", code: "PAK" },
  { name: "Palau", code: "PLW" },
  { name: "Palestine", code: "PSE" },
  { name: "Panama", code: "PAN" },
  { name: "Papua New Guinea", code: "PNG" },
  { name: "Paracel Islands", code: "Paracel Islands", noIso: true },
  { name: "Paraguay", code: "PRY" },
  { name: "Peru", code: "PER" },
  { name: "Philippines", code: "PHL" },
  { name: "Pitcairn Islands", code: "PCN" },
  { name: "Poland", code: "POL" },
  { name: "Portugal", code: "PRT" },
  { name: "Puerto Rico", code: "PRI" },
  { name: "Qatar", code: "QAT" },
  { name: "Republic of the Congo", code: "COG" },
  { name: "Reunion", code: "REU" },
  { name: "Romania", code: "ROU" },
  { name: "Russia", code: "RUS" },
  { name: "Rwanda", code: "RWA" },
  { name: "Saint Barthélemy", code: "BLM" },
  { name: "Saint Helena", code: "SHN" },
  { name: "Saint Kitts and Nevis", code: "KNA" },
  { name: "Saint Lucia", code: "LCA" },
  { name: "Saint Martin", code: "MAF" },
  { name: "Saint Pierre and Miquelon", code: "SPM" },
  { name: "Saint Vincent and the Grenadines", code: "VCT" },
  { name: "Samoa", code: "WSM" },
  { name: "San Marino", code: "SMR" },
  { name: "Sao Tome and Principe", code: "STP" },
  { name: "Saudi Arabia", code: "SAU" },
  { name: "Senegal", code: "SEN" },
  { name: "Serbia", code: "SRB" },
  { name: "Seychelles", code: "SYC" },
  { name: "Sierra Leone", code: "SLE" },
  { name: "Singapore", code: "SGP" },
  { name: "Sint Maarten", code: "SXM" },
  { name: "Slovakia", code: "SVK" },
  { name: "Slovenia", code: "SVN" },
  { name: "Solomon Islands", code: "SLB" },
  { name: "Somalia", code: "SOM" },
  { name: "South Africa", code: "ZAF" },
  { name: "South Georgia and the South Sandwich Islands", code: "SGS" },
  { name: "South Korea", code: "KOR" },
  { name: "South Sudan", code: "SSD" },
  { name: "Spain", code: "ESP" },
  { name: "Spratly Islands", code: "Spratly Islands", noIso: true },
  { name: "Sri Lanka", code: "LKA" },
  { name: "Sudan", code: "SDN" },
  { name: "Suriname", code: "SUR" },
  { name: "Svalbard", code: "SJM" },
  { name: "Swaziland", code: "SWZ" },
  { name: "Sweden", code: "SWE" },
  { name: "Switzerland", code: "CHE" },
  { name: "Syria", code: "SYR" },
  { name: "Taiwan", code: "TWN" },
  { name: "Tajikistan", code: "TJK" },
  { name: "Tanzania", code: "TZA" },
  { name: "Thailand", code: "THA" },
  { name: "The Bahamas", code: "BHS" },
  { name: "The Gambia", code: "GMB" },
  { name: "Timor-leste", code: "TLS" },
  { name: "Togo", code: "TGO" },
  { name: "Tokelau", code: "TKL" },
  { name: "Tonga", code: "TON" },
  { name: "Trinidad and Tobago", code: "TTO" },
  { name: "Tromelin Island", code: "ATF" },
  { name: "Tunisia", code: "TUN" },
  { name: "Turkey", code: "TUR" },
  { name: "Turkmenistan", code: "TKM" },
  { name: "Turks and Caicos Islands", code: "TCA" },
  { name: "Tuvalu", code: "TUV" },
  { name: "Uganda", code: "UGA" },
  { name: "Ukraine", code: "UKR" },
  { name: "United Arab Emirates", code: "ARE" },
  { name: "United Kingdom", code: "GBR" },
  { name: "United States", code: "USA" },
  { name: "Uruguay", code: "URY" },
  { name: "Uzbekistan", code: "UZB" },
  { name: "Vanuatu", code: "VUT" },
  { name: "Venezuela", code: "VEN" },
  { name: "Vietnam", code: "VNM" },
  { name: "Virgin Islands", code: "VIR" },
  { name: "Wake Island", code: "UMI" },
  { name: "Wallis and Futuna", code: "WLF" },
  { name: "West Bank", code: "PSE" },
  { name: "Western Sahara", code: "ESH" },
  { name: "Yemen", code: "YEM" },
  { name: "Zambia", code: "ZMB" },
  { name: "Zimbabwe", code: "ZWE" },
  { name: "Åland Islands", code: "ALA" }
];
